{{- if .Values.global.enterpriseEditionLicense }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: telemetry-cron
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "{{ .Values.telemetry.cron }}"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0 # Don't restart the failed jobs
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: telemetry-cron
            image: "{{ tpl .Values.telemetry.image.repository . }}:{{ .Values.telemetry.image.tag | default .Chart.AppVersion }}-ee"
            env:
              - name: LICENSE_KEY
                value: '{{ .Values.global.enterpriseEditionLicense }}'
              - name: version_number
                value: '{{ .Chart.AppVersion }}'
              - name: pg_host
                value: '{{ .Values.global.postgresql.postgresqlHost }}'
              - name: pg_port
                value: "5432"
              - name: pg_dbname
                value: "{{ .Values.global.postgresql.postgresqlDatabase }}"
              - name: pg_user
                value: '{{ .Values.global.postgresql.postgresqlUser }}'
              - name: pg_password
                value: '{{ .Values.global.postgresql.postgresqlPassword }}'
              - name: SITE_URL
                value: 'https://{{ .Values.global.domainName }}'
              - name: S3_HOST
                {{- if contains "minio" .Values.global.s3.endpoint }}
                value: 'https://{{ .Values.global.domainName }}:{{ .Values.global.ingress.controller.service.ports.https}}'
                {{- else}}
                value: '{{ .Values.global.s3.endpoint }}'
                {{- end}}
              - name: S3_KEY
                value: {{ .Values.global.s3.accessKey }}
              - name: S3_SECRET
                value: {{ .Values.global.s3.secretKey }}
              - name: AWS_DEFAULT_REGION
                value: '{{ .Values.global.s3.region }}'
              - name: sessions_region
                value: '{{ .Values.global.s3.region }}' 
              - name: sessions_bucket
                value: {{ .Values.global.s3.recordingsBucket }}
              - name: sourcemaps_bucket
                value: {{ .Values.global.s3.sourcemapsBucket }} 
              - name: js_cache_bucket
                value: {{ .Values.global.s3.assetsBucket }} 
              - name: EMAIL_HOST
                value: '{{ .Values.global.email.emailHost }}'
              - name: EMAIL_PORT
                value: '{{ .Values.global.email.emailPort }}'
              - name: EMAIL_USER
                value: '{{ .Values.global.email.emailUser }}'
              - name: EMAIL_PASSWORD
                value: '{{ .Values.global.email.emailPassword }}'
              - name: EMAIL_USE_TLS
                value: '{{ .Values.global.email.emailUseTls }}'
              - name: EMAIL_USE_SSL
                value: '{{ .Values.global.email.emailUseSsl }}'
              - name: EMAIL_SSL_KEY
                value: '{{ .Values.global.email.emailSslKey }}'
              - name: EMAIL_SSL_CERT
                value: '{{ .Values.global.email.emailSslCert }}'
              - name: EMAIL_FROM
                value: '{{ .Values.global.email.emailFrom }}'
              {{- range $key, $val := .Values.telemetry.env }}
              - name: {{ $key }}
                value: '{{ $val }}'
              {{- end}}
{{- end}}
